name: Testing date function

on:
  workflow_dispatch

jobs:
  output-date:
    runs-on: ubuntu-latest
    steps:
      - name: get-date
        id: date
        run: echo "::set-output name=date::$(date)"
        
      - name: output-date
        run: |
          echo "${{ steps.date.outputs.date }}"

        
  
  
